galacticcouncil/Basilisk-node

- Cargo.lock
- Cargo.toml
Basilisk uses orml dependencies from master branch. Since there was a change to use more recent substrate version  from different branch ( polkadot-v0.9.2) - doing any cargo update will result in having 2 different versions of substrate. 
Basilisk is currently built with substrate from branch polkadot-v0.9.1
Therefore, this PR pins the orml to specific revision where the same version of substrate is used.
> chore: pin orml to specific revision

- pallets/nft/src/benchmarking.rs
- pallets/nft/src/lib.rs
- pallets/nft/src/mock.rs
- runtime/src/lib.rs
Removed `CurrencyBalance` from pallet config as it is not necessary ( used only in benchmarks).
> refactor(nft): remove unnecessary currencybalance from pallet config

- .github/workflows/tests.yml
- rust-toolchain
Toolchain updated to more recent version.
Reasons:
- same as in HydraDX
- same as in GH workflow 
- no longer possible to compile some stuff with the older one.
> chore: update rust-toolchain

- Cargo.lock
- pallets/xyk/Cargo.toml
- pallets/xyk/src/lib.rs
- pallets/xyk/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Create pool only if both amounts are greater than `MIN_POOL_LIQUIDITY`.
> fix(xyk): create_pool respects min liquidity limit

- .codecov.yml
- pallets/transaction-multi-payment/src/lib.rs
- pallets/transaction-multi-payment/src/tests.rs
- runtime/src/lib.rs
Added signed extension for multi-payment pallet to check account balance when set_currency call is executed.
Balance must  > 0 atm.
> feat: balance check as signed extension

- node/res/basilisk-vesting-lbp-test.json
Benchmarking fails because VestingConfig in [parachain_development_config](https://github.com/galacticcouncil/Basilisk-node/blob/ef5a731fdbc77e0a076cc0709ea532f854a8f1c7/node/src/chain_spec.rs#L291) contains non-endowed account (Charlie). The issue is fixed by removing the account from `node/res/basilisk-vesting-lbp-test.json` file.
An alternative solution is to use different account( e.g. Alice//stash or Bob//stash).
> fix(vesting): fix benchmarking

- rococo-local/config.json
Added an extra parachain node to the rococo-local `config.json`, otherwise the subsquid indexer would not connect normally or blocks would not be produced on the parachain.
Added an extra parachain node to the rococo-local testnet config with additional cli options.
Implements: #164
You can test that the rococo-local setup still works by running `polkadot-launch config.json`
> feat: Added an extra node to the rococo-local config

- Cargo.lock
- node/src/chain_spec.rs
- pallets/transaction-multi-payment/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/src/lib.rs
- pallets/transaction-multi-payment/benchmarking/src/mock.rs
- pallets/transaction-multi-payment/src/lib.rs
- pallets/transaction-multi-payment/src/mock.rs
- pallets/transaction-multi-payment/src/tests.rs
- pallets/transaction-multi-payment/src/weights.rs
- runtime/src/lib.rs
- runtime/src/weights/asset_registry.rs
- runtime/src/weights/payment.rs
- runtime/src/xcm.rs
Builder review suggestions to use origin check rather than having a list of authorities which can add or remove accepted currency.
Also consolidated multi-payment config.
> refactor: improve multi payment (builder review)

- README.md
Added xcm types to readme to set it to V0 ( by default it is v1 )
Also updated asset type enum to include share token.
> chore: update xcm v0 types in readme [skip ci]

- pallets/lbp/src/lib.rs
- pallets/lbp/src/tests.rs
Implement a test simulating an LBP event
Fixes: #70
> feat(lbp): add simulation test

- pallets/duster/src/lib.rs
- runtime/src/lib.rs
Updated orml-tokens list of non-dustable accounts. 
It actually uses the duster list as it is duster who handles all the details regarding dust and dusting.
Currenly, on Basilisk - there is only treasury account.
> fix: update orml-tokens whitelist accounts

- .github/workflows/tests.yml
- Makefile
> feat: create makefile

- runtime/basilisk/src/adapter.rs
- runtime/basilisk/src/lib.rs
Added orml-tokens adapter for currencies. 
It emits Tokens::Transfer event when currencies::transfer is executed.
It is needed to stay consistent when making transfer via Tokens,Balances,Currencies pallets.
> feat: orml-tokens adapter

- Cargo.lock
- node/Cargo.toml
- node/src/command.rs
Throws an error with a message when trying to start a collator node built with the `runtime-benchmarks` flag.
Fixes: #208
> feat: disallow collating with benchmarking runtime

- node/src/chain_spec.rs
Updated registered assets in dev chainspec. 
KSM and KUSD are 2 registered assets. 
And both are enabled to be selected as currency to pay tx fee with with following prices:
1 BSX = 0.00806 KUSD
1 BSX = 0.0000212 KSM
> chore: update registered currencies in dev chainspec

- node/src/chain_spec.rs
- node/src/testing_chain_spec.rs
- pallets/duster/src/lib.rs
- pallets/exchange/benchmarking/src/mock.rs
- pallets/exchange/src/direct.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/mock.rs
- pallets/lbp/src/benchmarking.rs
- pallets/lbp/src/lib.rs
- pallets/lbp/src/mock.rs
- pallets/lbp/src/tests.rs
- pallets/transaction-multi-payment/benchmarking/src/mock.rs
- pallets/transaction-multi-payment/src/mock.rs
- pallets/xyk/src/lib.rs
- pallets/xyk/src/mock.rs
- primitives/src/traits.rs
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/src/lib.rs
> refactor: AssetPairAccountId trait

- Cargo.lock
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
CurrentBlockNumbers event to give info about current block numbers could not be sent in the on_init as the validation is not yet set.
The deposit event called have been moved to OnValidateData handler which is triggered when this data is set.
> fix: relaychain number in info event

- .github/workflows/tests.yml
before there were actually 2 toolchains installed, but the only one specified in toolchain file was used. i have changed the action to the fixed one that is able to install just the toolchain that is actually used.
---
fixes #255
> ci: install toolchain according to file

- pallets/auctions/src/mock.rs
- pallets/auctions/src/tests.rs
- pallets/auctions/src/traits.rs
- rust-toolchain
The PR refactors the tests for pallet_auctions:
* introduces a `predefined_test_ext()` for DRY code
* splits test cases into separate functions for better readibility and debug
> chore: Refactor NFT Auctions tests

- pallets/auctions/src/lib.rs
- pallets/auctions/src/mock.rs
- pallets/auctions/src/tests.rs
- pallets/auctions/src/traits.rs
- runtime/basilisk/src/lib.rs
Resolves https://github.com/galacticcouncil/Basilisk-node/issues/309
Resolves https://github.com/galacticcouncil/Basilisk-node/issues/332
This PR:
* adds a reserve_price (RP) functionality to NFT auctions
* adds a validation for the starting bid (next_bid_min at create/update) which should always be greater than a predefined minimum to prevent attack vectors 
* extends tests for create / update / delete Auction::TopUp
How the RP is implemented:
* English: the RP serves as a starting bid - no bids under the RP are accepted
* TopUp: bids under the RP are accepted, however the auction is only won if the sum of bids has reached the reserve_price (to be implemented after TopUp refactor)
> feat: Add reserve_price to auctions and tests for Auction::TopUp

- Cargo.lock
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
PR makes sure that each pallet in runtime is assigned persistent id. 
This makes sure that module ids are the same when a pallet is either removed or added. 
I decided to group ids as follows:
- starting at 0 - substrate related pallets
- starting at 50 - parachain and xcm related stuff
- stating at 100 - basilisk pallets and warehouse pallets
- starting at 150 - orml
- starting at 200 - testing stuff - pallets which are not present in basilisk, only in testing runtime
The reasons being:
- allows quicker identify area of an error
- allows adding new pallets to be together with related stuff
- order is also important - therefore having some spaces prevents unwanted shifts in future. 
Note that the order of pallets is important. 
Eg. 
- Session must be after collator selection and prior to …
> refactor: pin runtime pallet ids

- scripts/list_crate_updates.sh
Fix: version check always reports that runtime versions don't match.
> ci: fix runtime version match check

- pallets/auctions/src/lib.rs
- pallets/auctions/src/mock.rs
- pallets/auctions/src/tests.rs
- pallets/auctions/src/traits.rs
- pallets/auctions/src/weights.rs
- runtime/basilisk/src/lib.rs
- runtime/common/src/lib.rs
- runtime/src/weights/auctions.rs
This PR builds on https://github.com/galacticcouncil/Basilisk-node/pull/308
It delivers the missing pieces for finishing TopUp auctions
When a user bids on a topup auction, the amount which is bid is reserved (ie moved to a subaccount belonging to the auction). 
At auction close, the whole amount is transferred to the seller in case the lot is sold (ie reserve_price is met)
If there is no winner because the reserve price was not met, all bidders can claim back their (aggregated) reserved amounts
TODO: 
* Add documentation
> refactor: TopUp Auction

- scripts/list_crate_updates.sh
Fix: version check always reports that runtime versions don't match.
> ci: runtime version match check fixed

- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
`cargo check -p basilisk-runtime` was failing when trying to compile `pallet-proxy` and I noticed it was missing in the std feature list for the runtime.
> fix: add missing pallet-proxy in std feature

- Cargo.lock
- pallets/liquidity-mining/Cargo.toml
- pallets/liquidity-mining/src/lib.rs
> feat: ensure liquidity mining NFT id is within reserved range

- runtime/basilisk/Cargo.toml
- runtime/testing-basilisk/Cargo.toml
with recent changes - it was not possible to build basilisk-runtime or testing-basilisk which result in CI build failing ( it attempts to build standalone runtime).
> chore: fix runtime builds - basilisk and testing-basilisk

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/kusama_test_net.rs
- integration-tests/src/non_native_fee.rs
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/testing_chain_spec.rs
- pallets/exchange/Cargo.toml
- pallets/exchange/benchmarking/Cargo.toml
- pallets/lbp/Cargo.toml
- pallets/liquidity-mining/Cargo.toml
- pallets/liquidity-mining/benchmarking/Cargo.toml
- pallets/offchain-duster/Cargo.toml
- pallets/xyk/Cargo.toml
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/benchmarking/multi_payment.rs
- runtime/basilisk/src/lib.rs
- runtime/common/Cargo.toml
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
Use the `TransferFees` type introduced in https://github.com/galacticcouncil/warehouse/pull/42 in the runtimes and fix various type/integration issues.
Fixes: #412
This transfers fees to the treasury instead of burning them.
In addition it also unblocks other PRs depending on a recent version of the warehouse.
> feat!: Transfer Fees to Treasury

- Cargo.lock
- pallets/exchange/Cargo.toml
- pallets/lbp/Cargo.toml
- pallets/xyk/Cargo.toml
- pallets/xyk/src/benchmarking.rs
- pallets/xyk/src/lib.rs
- pallets/xyk/src/mock.rs
- pallets/xyk/src/tests.rs
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
Shares calculation in add_liquidity has been changed. 
it is now calculated as follows:
delta_shares = share_issuance * delta_X / reserve_x 
where X is an asset provided by LP. 
it was also moved to the math crate so xyk now calls only calculate_shares from the xyk math module. 
requires https://github.com/galacticcouncil/HydraDX-math/pull/42/files
> fix: xyk shares calculation

- Cargo.lock
- pallets/xyk/Cargo.toml
- pallets/xyk/src/lib.rs
Price oracle handler (AMMHandler) shouldn't throw an unhandled error in XYK pallet.
> fix: ignore AMMHandler error

- Cargo.lock
- primitives/Cargo.toml
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
primitives crates should avoid including complex dependencies where possible
> fix!: remove pallet deps from primitives crate

- Cargo.lock
- pallets/xyk-liquidity-mining/Cargo.toml
- pallets/xyk-liquidity-mining/src/migration.rs
Creation of NFT collection for xyk LM pallet was removed from migration. This collection is already exists on Rococo and Basilisk.
> chore: remove creation of nft collection from LM migration

- Cargo.lock
- node/Cargo.toml
- node/src/command.rs
Fix: `base_path()` uses temp dir when `-tmp` param is used
> fix: base_path uses tmp dir

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/parachain-runtime-mock/Cargo.toml
- pallets/duster/Cargo.toml
- pallets/lbp/Cargo.toml
- pallets/marketplace/Cargo.toml
- pallets/xyk-liquidity-mining/Cargo.toml
- pallets/xyk-liquidity-mining/benchmarking/Cargo.toml
- pallets/xyk-liquidity-mining/src/lib.rs
- pallets/xyk-liquidity-mining/src/tests/mock.rs
- pallets/xyk-liquidity-mining/src/tests/redeposit_shares.rs
- pallets/xyk/Cargo.toml
- primitives/Cargo.toml
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/common/Cargo.toml
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
This PR updates repo to latest warehouse and fixes bug in liquidity-mining's `redeposit_lp_shares()` function.
`AssetPair` provided to `redeposit_lp_shares()` by users  is not checked with `Deposit` so users can provide different `AssetPair` than is `Deposit` for. 
This can result in wrong information in the event or/and bypassing xyk pool existence check.
Check `amm_pool_id` from the deposit with `amm_pool_id` generated from `AssetPair`.
> fix: lm redeposit_lp_shares()

- Cargo.lock
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
This PR moves `Scheduler` pallet after `ParachainSystem` so we have access to relaychain block numbers in `Scheduler`.
Tested:
* runtime upgrade 91 -> 92
* LM create yield farm using democracy
* runtime upgrade 92 -> 93 (only spec version change)
* runtime upgrade 93 -> 94 (only spec version change)
> fix: sheduler has validation data from previous block available

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/parachain-runtime-mock/Cargo.toml
- pallets/lbp/Cargo.toml
- pallets/marketplace/Cargo.toml
- pallets/xyk-liquidity-mining/Cargo.toml
- pallets/xyk-liquidity-mining/benchmarking/Cargo.toml
- pallets/xyk/Cargo.toml
- pallets/xyk/src/tests/creation.rs
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/benchmarking/marketplace.rs
- runtime/basilisk/src/benchmarking/mod.rs
- runtime/basilisk/src/lib.rs
- runtime/basilisk/src/migrations.rs
- runtime/common/Cargo.toml
- runtime/testing-basilisk/Cargo.toml
- runtime/testing-basilisk/src/lib.rs
Add a migration for the asset registry that removes `locked` and introduces `xcm_rate_limit`.
https://github.com/galacticcouncil/warehouse/pull/209
> feat: asset registry xcm rate limit

- Cargo.lock
- pallets/xyk/Cargo.toml
- pallets/xyk/src/tests/spot_price.rs
Tests were broken on master, probably due to merging #614 
This adjusts the tests to the new asset order for the `spot_price` function.
> test: spot price tests fixed

- Cargo.lock
- pallets/marketplace/Cargo.toml
- pallets/marketplace/src/lib.rs
- pallets/marketplace/src/types.rs
This PR removes `without_storage_info` from the Marketplace pallet.
> feat(Marketplace): bounded storage

- Cargo.lock
- pallets/lbp/Cargo.toml
- pallets/lbp/src/lib.rs
This PR removes `without_storage_info` from the LBP pallet.
> feat(LBP): bounded storage

- fork-testing/README.md
I got tripped up a little trying to figure out how a parchain was different from a parachain, until I realized it was just a typo. Made this fix so it doesn't mess anyone up in the future.
> docs: clarify fork testing

- Cargo.lock
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/governance/mod.rs
- runtime/basilisk/src/lib.rs
- runtime/basilisk/src/system.rs
This PR refactors the TechnicalCommittee origins and enables it to post referenda to the whitelisted track
> fix: Update TechComm origins

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/kusama_test_net.rs
- integration-tests/src/lib.rs
- integration-tests/src/sessions.rs
- runtime/basilisk/Cargo.toml
- runtime/basilisk/src/lib.rs
- runtime/basilisk/src/system.rs
fixes: https://github.com/galacticcouncil/Basilisk-node/issues/673
> feat: rotate collator order each session
