galacticcouncil/Basilisk-node

Cargo.lock
Cargo.toml
README.md
node/src/chain_spec.rs
node/src/command.rs
rococo-local/config.json
runtime/Cargo.toml
runtime/src/lib.rs

feat: vesting

---

Cargo.lock
runtime/Cargo.toml
runtime/src/lib.rs

feat: utility

---

Cargo.lock
node/src/chain_spec.rs
runtime/Cargo.toml
runtime/src/lib.rs

Use latest HydraDX pallets.
Fixes in exchange algorithm
Multi-payment pallet implements new feature to add possibility to set a price for accepted currencies which is used when pool does not exist yet ( #45  )

chore!: update hydra dependencies - use latest pallets

---

Cargo.lock

Fixed to: Parachain stopped sync relaychain network with error:
```
Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', /home/frido/.cargo/git/checkouts/substrate-7e08433d4c370a21/3bb42b9/primitives/io/src/lib.rs:1100
Jun 24 11:52:06 westend-collator-01 basilisk[77582]: This is a bug. Please report it at:
Jun 24 11:52:06 westend-collator-01 basilisk[77582]:         https://github.com/galacticcouncil/Basilisk-node/issues
Jun 24 11:52:06 westend-collator-01 basilisk[77582]: 2021-06-24 11:52:06 [Relaychain] Block prepare storage changes error:
Jun 24 11:52:06 westend-collator-01 basilisk[77582]: RuntimeApiError(Application(Execution(Other("Wasm execution trapped: Failed to allocate memory: \"Requested allocation size is too …
```

fix: cargo update

---

.github/workflows/tests.yml

ci: add code test coverage

---

Cargo.lock
pallets/exchange/benchmarking/src/lib.rs
pallets/exchange/src/lib.rs
pallets/exchange/src/tests.rs
pallets/lbp/Cargo.toml
pallets/xyk/Cargo.toml
pallets/xyk/src/benchmarking.rs
pallets/xyk/src/lib.rs
pallets/xyk/src/tests.rs

HydraDX-math has been updated to fix a bug.

chore: use latest math package

---

.github/workflows/tests.yml

run GH worfklow on push to master ( useful for test coverage report).

ci: run workflow on push to master

---

pallets/xyk/src/lib.rs
pallets/xyk/src/tests.rs

Add missing tests found by code coverage tools.

test(xyk): add missing tests

---

pallets/exchange/src/lib.rs
pallets/exchange/src/tests.rs

Add missing tests found by code coverage tools.

test(exchange): add missing tests

---

Cargo.lock
pallets/lbp/Cargo.toml
pallets/lbp/src/lib.rs
pallets/lbp/src/tests.rs
pallets/xyk/Cargo.toml

chore: use latest math crate

---

pallets/transaction-multi-payment/benchmarking/src/lib.rs
pallets/transaction-multi-payment/src/tests.rs
pallets/xyk/src/lib.rs
pallets/xyk/src/mock.rs
pallets/xyk/src/tests.rs
primitives/src/lib.rs

feat: add trading limits to xyk pool

---

.codecov.yml

Taming codecov by adjusting thresholds

ci: add codecov yml to adjust thresholds

---

Cargo.lock
pallets/exchange/src/tests.rs
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
pallets/xyk/src/tests.rs

feat: update xyk events

---

.github/workflows/tests.yml
node/src/chain_spec.rs
node/src/command.rs
pallets/asset-registry/src/benchmarking.rs
pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/tests.rs
pallets/duster/src/lib.rs
pallets/exchange/benchmarking/src/mock.rs
pallets/exchange/src/lib.rs
pallets/exchange/src/mock.rs
pallets/exchange/src/tests.rs
pallets/lbp/src/benchmarking.rs
pallets/lbp/src/lib.rs
pallets/lbp/src/mock.rs
pallets/lbp/src/tests.rs
pallets/nft/src/benchmarking.rs
pallets/nft/src/lib.rs
pallets/transaction-multi-payment/benchmarking/src/lib.rs
pallets/transaction-multi-payment/benchmarking/src/mock.rs
pallets/transaction-multi-payment/src/lib.rs
pallets/transaction-multi-payment/src/mock.rs
pallets/xyk/src/benchmarking.rs
pallets/xyk/src/mock.rs
pallets/xyk/src/tests.rs
primitives/src/traits.rs
runtime/src/lib.rs
runtime/src/tests.rs

Resolve all clippy warnings and add clippy to github workflow

ci: add clippy

---

Cargo.lock
pallets/exchange/src/direct.rs
pallets/lbp/Cargo.toml
pallets/lbp/src/lib.rs
pallets/transaction-multi-payment/src/lib.rs
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
primitives/src/lib.rs
runtime/src/lib.rs

Audit findings - minor issues.

fix: audit changes

---

pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/tests.rs

Instead of 0, set MAX value for unsupported assets.

fix: set ED to max value for unsupported assets

---

node/src/testing_chain_spec.rs
runtime/testing-basilisk/src/adapter.rs
runtime/testing-basilisk/src/lib.rs

Updated testing runtime:
- chain spec to match the runtime chain spec
- orml token adapter

fix: update testing runtime

---

pallets/exchange/src/tests.rs
pallets/xyk/src/lib.rs
pallets/xyk/src/tests.rs

feat: change the order of emitted events for xyk pools

---

node/src/command.rs
node/src/testing_chain_spec.rs

Add option to build chainspec for k8s testnet from testing runtime.
`./target/release/testing-basilisk build-spec --chain testnet-k8s --raw > basilisk-raw.json`

feat: testnet-k8s chain

---

Cargo.lock
pallets/asset-registry/Cargo.toml
pallets/exchange/Cargo.toml
pallets/exchange/benchmarking/Cargo.toml
pallets/lbp/Cargo.toml
pallets/lbp/src/lib.rs
pallets/transaction-multi-payment/Cargo.toml
pallets/transaction-multi-payment/benchmarking/Cargo.toml
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
runtime/basilisk/Cargo.toml
runtime/testing-basilisk/Cargo.toml

Implements AMM::get_share_token for xyk and lbp ( although lbp does not have any ).

chore: update to latest hydradx-traits

---

rococo-local/basilisk-karura.json

Updated 2 parachains config to make sure it works. With the current one - BSX could not produce any blocks.

fix: update two parachain config 

---

pallets/lbp/src/lib.rs
pallets/lbp/src/tests.rs

Resolves https://github.com/galacticcouncil/Basilisk-node/issues/284

feat: Add validation on existing fee collector

---

infrastructure/infra.tf

*AMI Image with new Github Key

ci: update ami image with new key

---

Cargo.lock
pallets/asset-registry/Cargo.toml
pallets/asset-registry/src/benchmarking.rs

fix: update asset registry benchmarks

---

Cargo.lock
pallets/asset-registry/Cargo.toml
pallets/asset-registry/src/benchmarking.rs
pallets/exchange/Cargo.toml
pallets/exchange/benchmarking/Cargo.toml
pallets/exchange/src/direct.rs
pallets/lbp/Cargo.toml
pallets/lbp/src/lib.rs
pallets/lbp/src/tests.rs
pallets/transaction-multi-payment/Cargo.toml
pallets/transaction-multi-payment/benchmarking/Cargo.toml
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
pallets/xyk/src/mock.rs
pallets/xyk/src/tests.rs
runtime/basilisk/Cargo.toml
runtime/common/Cargo.toml
runtime/testing-basilisk/Cargo.toml

feat(exchange): use fee from amm

---

node/src/testing_chain_spec.rs

New keys for k8s testnet and smaller collator set.

feat: new keys for k8s testnet

---

Cargo.lock
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/basilisk/src/xcm.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs
runtime/testing-basilisk/src/xcm.rs

Added orml-xcm pallet which contains some helper function. 
It is mainly to help with proposals to open channels between chains.

feat: add orml xcm pallet

---

.github/workflows/workflow.yml

ci: check fails if versions are not updated

---

.github/workflows/workflow.yml

Fixes the bug that was causing runners not to be destroyed during the destroy step

ci: fixed runner destroy

---

docs/kintsugi_integration.md
rococo-local/basilisk-kintsugi.json

feat: kintsugi integration

---

Cargo.lock
pallets/lbp/Cargo.toml
pallets/lbp/src/mock.rs
pallets/lbp/src/tests.rs

refactor: rename run_to_block to set_block_number

---

.github/workflows/docs.yml

ci: generate and deploy rust docs

---

pallets/auctions/src/lib.rs
pallets/auctions/src/mock.rs
pallets/auctions/src/tests.rs
pallets/auctions/src/traits.rs
pallets/auctions/src/weights.rs
runtime/basilisk/src/lib.rs
runtime/src/weights/auctions.rs
runtime/testing-basilisk/src/lib.rs

Resolves #388 
Candle auction + refactor
TODO: docs

feat: Candle Auction

---

integration-tests/src/cross_chain_transfer.rs
integration-tests/src/kusama_test_net.rs
integration-tests/src/non_native_fee.rs
node/src/chain_spec.rs
node/src/testing_chain_spec.rs
primitives/src/lib.rs
runtime/testing-basilisk/src/lib.rs

chore: reformat src

---

Cargo.lock
Cargo.toml
integration-tests/src/non_native_fee.rs

Incorrect warehouse version used.

bug: fix non native fee calcs

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs

feat: karura testnet chainspec

---

runtime/basilisk/src/lib.rs

Typo in multi payment benchmark module in benchmarks config.

fix: fix  multi paymnet benchmark config

---

.github/workflows/docs.yml

docs: Generate CNAME file in docs workflow

---

Cargo.lock
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

feat: disable XCM calls

---

node/src/testing_chain_spec.rs

style: formatting

---

Cargo.lock
Makefile
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
rust-toolchain

Bump to nightly-2022-02-19-x86_64

chore: bump rust toolchain

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/src/cross_chain_transfer.rs
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/basilisk/src/xcm.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs
runtime/testing-basilisk/src/xcm.rs

feat: Use GeneralIndex for our xchain assets

---

integration-tests/Cargo.toml

bug: only use one slash for warehouse dep

---

Cargo.lock
Makefile
integration-tests/Cargo.toml
runtime/basilisk/Cargo.toml
runtime/testing-basilisk/Cargo.toml

build: enable all features

---

Cargo.lock
pallets/exchange/Cargo.toml
pallets/exchange/benchmarking/Cargo.toml
pallets/exchange/benchmarking/src/mock.rs
pallets/exchange/src/mock.rs
pallets/exchange/src/tests.rs
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
pallets/xyk/src/mock.rs
pallets/xyk/src/tests.rs
primitives/Cargo.toml
primitives/src/constants.rs
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/common/Cargo.toml
runtime/common/src/lib.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

Make the discounted fee configurable instead of using hardcoded value.

refactor: discounted fee

---

runtime/testing-basilisk/src/lib.rs

fix: use native asset in tx multi payment config

---

Cargo.lock
integration-tests/Cargo.toml
pallets/marketplace/Cargo.toml
pallets/marketplace/src/benchmarking.rs
pallets/marketplace/src/lib.rs
pallets/marketplace/src/mock.rs
pallets/marketplace/src/tests/make_offer.rs
pallets/marketplace/src/tests/mod.rs
pallets/marketplace/src/tests/unit.rs
primitives/Cargo.toml
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/common/Cargo.toml
runtime/common/src/lib.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

also little bit of test changes that we did on Friday hack
dependent of https://github.com/galacticcouncil/warehouse/pull/65

feat: NFT marketplace uses relay chain currency

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/src/kusama_test_net.rs
integration-tests/src/non_native_fee.rs
pallets/exchange/Cargo.toml
pallets/exchange/benchmarking/Cargo.toml
pallets/lbp/Cargo.toml
pallets/offchain-duster/Cargo.toml
pallets/xyk/Cargo.toml
runtime/basilisk/Cargo.toml
runtime/common/Cargo.toml
runtime/testing-basilisk/Cargo.toml

fee currency should not change when account holds native currency already
related to the #454

fix: fee currency change

---

integration-tests/Cargo.toml
integration-tests/src/lib.rs
integration-tests/src/xyk.rs
runtime/basilisk/src/lib.rs

Added integration tests to check if pool account is added/removed from duster whitelist

feat: XYK integration tests 

---

Cargo.lock
integration-tests/Cargo.toml
pallets/duster/Cargo.toml
pallets/exchange/Cargo.toml
pallets/exchange/benchmarking/Cargo.toml
pallets/lbp/Cargo.toml
pallets/marketplace/Cargo.toml
pallets/offchain-duster/Cargo.toml
pallets/xyk/Cargo.toml
primitives/Cargo.toml
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/common/Cargo.toml
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

Updates to latest warehouse version.
Fixes #539

fix: NFT events change reintroduced

---

Cargo.lock
pallets/marketplace/Cargo.toml
pallets/marketplace/src/tests/make_offer.rs
pallets/marketplace/src/tests/withdraw_offer.rs

test(marketplace): add missing test

---

Cargo.lock
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

feat: whitelist treasury in benchmarks

---

Cargo.lock
pallets/marketplace/Cargo.toml
pallets/marketplace/src/benchmarking.rs
pallets/marketplace/src/lib.rs
pallets/marketplace/src/migration.rs
pallets/marketplace/src/tests/accept_offer.rs
pallets/marketplace/src/tests/add_royalty.rs
pallets/marketplace/src/tests/buy.rs
pallets/marketplace/src/types.rs

feat: royalty type

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/parachain-runtime-mock/Cargo.toml
integration-tests/src/nft.rs
node/Cargo.toml
node/src/chain_spec.rs
node/src/testing_chain_spec.rs
pallets/duster/Cargo.toml
pallets/lbp/Cargo.toml
pallets/marketplace/Cargo.toml
pallets/marketplace/src/lib.rs
pallets/marketplace/src/mock.rs
pallets/xyk-liquidity-mining/Cargo.toml
pallets/xyk-liquidity-mining/benchmarking/Cargo.toml
pallets/xyk-liquidity-mining/benchmarking/src/lib.rs
pallets/xyk-liquidity-mining/benchmarking/src/mock.rs
pallets/xyk/Cargo.toml
primitives/Cargo.toml
primitives/src/constants.rs
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/common/Cargo.toml
runtime/common/src/lib.rs
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

This PR:
* updates all the pallets to use latest warehouse repo.
* adding check for `native_existential_deposit` configuration in relation to liquidity mining.
This PR is continuation of https://github.com/galacticcouncil/warehouse/pull/116 .

feat: non dustable liquidity mining 

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/parachain-runtime-mock/Cargo.toml
node/Cargo.toml
pallets/duster/Cargo.toml
pallets/lbp/Cargo.toml
pallets/marketplace/Cargo.toml
pallets/xyk-liquidity-mining/Cargo.toml
pallets/xyk-liquidity-mining/benchmarking/Cargo.toml
pallets/xyk-liquidity-mining/src/tests/mock.rs
pallets/xyk/Cargo.toml
pallets/xyk/src/lib.rs
primitives/Cargo.toml
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs
runtime/common/Cargo.toml
runtime/testing-basilisk/Cargo.toml
runtime/testing-basilisk/src/lib.rs

Update warehouse deps to current warehouse main and update xyk pallet on trade handler
Make sure Basilisk compiles and works with warehouse master.

chore!: update warehouse deps and update xyk pallet on trade handler

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/src/call_filter.rs
integration-tests/src/lib.rs

The tests were not included in the lib.

fix: call filter tests

---

Cargo.lock
pallets/xyk-liquidity-mining/benchmarking/Cargo.toml
pallets/xyk-liquidity-mining/benchmarking/src/mock.rs

This PR fixes tests for xyk-liquidity-mining benchmarks

test: fix LM benchmarks

---

Cargo.lock
runtime/basilisk/Cargo.toml
runtime/basilisk/src/lib.rs

chore: use workspace dep for pallet collator rewards

---

Cargo.lock
runtime/basilisk/Cargo.toml
runtime/basilisk/src/governance.rs
runtime/basilisk/src/lib.rs

Fixes #611 and short tip execution time

fix: update council voting params and tip execution delay
